### ISSUE TITLE
Remove instances of unwraps

### ISSUE THREAD

**Issue by vaibhawvipul** [spacewalkhq/raft-rs#16]
- remove all occurrence of unchecked unwraps. 
- unwraps cause panic, we want to gracefully handle the errors.

**Comment by rishitc** [comment]
Hi,
I'm interested in working on this issue.

Can it be assigned to me?

Thanks

**Comment by rishitc** [comment]
Hi @vaibhawvipul,
I'm currently getting familiar with the codebase. While I'm in this process, I am curious to know whether there is a specific expectation about what the `unwrap`s should be replaced by.

Would it be correct to say that on a high level, except for unrecoverable scenarios, our idea is to: 

- Remove `unwrap` and instead bubble up all the errors to the callers where we can either
  1. Handle the error
OR
  1. The error eventually reaches back up to the `main` function, where we return the error and terminate the program.

Thanks

**Comment by dierbei** [comment]
My idea was to return to the function call for error logging.

```rust
    if let err = match value {
        error!("Matched Variant1");
        return;
    }
```

**Comment by vaibhawvipul** [comment]
@rishitc any progress here?

**Comment by rishitc** [comment]
Hi @vaibhawvipul,
Thanks for checking in 😄 

Here's a brief progress report:
1. After the 7th of August, I spent time understanding the codebase.
    1. Finished about 50% of the task. 
1. I was busy in the first half of this week, so I'm working on finishing off my codebase deep dive this weekend.
    1. If I have any questions about the codebase, I'll post them on the Discussion Forum of the GitHub project _(I'll probably post all of them over this weekend)_.
1. Regarding how to handle the errors, @dierbei's [reply](https://github.com/spacewalkhq/raft-rs/issues/16#issuecomment-2272504820) clarified my doubts 👍 

Thanks

**Comment by rishitc** [comment]
Based on the source code I reviewed till date; I think I'm all set to get started with working on the first PR draft.

I'll start working on that tomorrow 👍

**Comment by rishitc** [comment]
Hi @vaibhawvipul,
I'll put up my draft PR by 27th August end of the day so that it is easier to track progress and provide feedback 🙂

Thanks

**Comment by vaibhawvipul** [comment]
> Hi @vaibhawvipul, I'll put up my draft PR by 27th August end of the day so that it is easier to track progress and provide feedback 🙂
> 
> Thanks

Excited! :)

**Comment by rishitc** [comment]
Hi @vaibhawvipul,
The first draft of my PR is up for review.
I've covered most of the cases of `unwrap` except the ones dealing with slicing vectors, as I'm not sure about the possible way(s) of error handling such cases without panicking.

Requesting your comments on the changes made in the PR #36.
It'll help me understand whether I'm on the right track or need to course-correct.

Thanks
