### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by vaibhawvipul** [spacewalkhq/raft-rs#3]
Add unit tests to the following files 

- storage.rs
- network.rs
- server.rs

**Comment by dharanad** [comment]
I would like to work on this, but it will take some time. If that's okay please do assign it to me

**Comment by vaibhawvipul** [comment]
Assigning this to @dharanad  now. Keep making small progress. I would love to see a PR with incremental changes. Tackle things file by file.

**Comment by vaibhawvipul** [comment]
Please keep the tests in the same file. 

For example, storage.rs tests should be at the end of the file. not in a new file.

**Comment by dharanad** [comment]
@vaibhawvipul I will be to adding UT `server` in seperate PR.

**Comment by vaibhawvipul** [comment]
> @vaibhawvipul I will be to adding UT `server` in seperate PR.

sure. Please open a ticket for that, if you can.

**Comment by dharanad** [comment]
> > @vaibhawvipul I will be to adding UT `server` in seperate PR.
> 
> sure. Please open a ticket for that, if you can.

This this over here https://github.com/spacewalkhq/raft-rs/issues/21
